//USER ACTIONS
export const REQUEST_USER_WORKSPACES_PENDING =
  "REQUEST_USER_WORKSPACES_PENDING";
export const REQUEST_USER_WORKSPACES_SUCCESS =
  "REQUEST_USER_WORKSPACES_SUCCESS";
export const REQUEST_USER_WORKSPACES_FAILED = "REQUEST_USER_WORKSPACES_FAILED";
